---
title: "Chapter4_code"
author: "Chelsea Helion"
date: "12/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
```

## code to create running average plot
```{r}
## run original program
setwd(here::here("data/DBDA2Eprograms"))
source("RunningProportion.R")

## play around with setting a new seed
source("DBDA2E-utilities.R")
set.seed(8587)
openGraph(width=7, height = 6)
source("RunningProportion.R")
saveGraph(here::here("figs", "RunningProportionExample.jpg"))
```
## Exercise 4.1
```{r}
 # show data
show(HairEyeColor)
# sum across sex
EyeHairFreq = apply(HairEyeColor, c("Eye", "Hair"), sum)
# joint proportions (i.e., what percent of the sample has each combination)
EyeHairProp = EyeHairFreq/sum(EyeHairFreq)
EyeHairFreq
EyeHairProp 

# round to the second decimal place
show(round(EyeHairProp, 2))

#separate out hair color
HairFreq = apply(HairEyeColor, c("Hair"), sum)
HairProp = HairFreq/sum(HairFreq)
show(round(HairProp, 2))


# separate out eye color
EyeFreq = apply(HairEyeColor, c("Eye"), sum)
EyeProp = EyeFreq/sum(EyeFreq)
show(round(EyeProp, 2))
# calculate conditional probability
EyeHairProp["Blue",]/EyeProp["Blue"]
```
## Exercise 4.2
```{r}
N = 500 # Specify the total number of flips, denoted N.
pHeads = 0.8 # Specify underlying probability of heads.
# Flip a coin N times and compute the running proportion of heads at each flip.
# Generate a random sample of N flips (heads=1, tails=0):
flipSequence = sample( x=c(0,1), prob=c(1-pHeads,pHeads), size=N, replace=TRUE )
# Compute the running proportion of heads:
r = cumsum( flipSequence ) # Cumulative sum: Number of heads at each step.
n = 1:N                    # Number of flips at each step.
runProp = r / n            # Component by component division.
# Graph the running proportion:
plot( n , runProp , type="o" , log="x" , col="skyblue" ,
      xlim=c(1,N) , ylim=c(0.0,1.0) , cex.axis=1.5 ,
      xlab="Flip Number" , ylab="Proportion Heads" , cex.lab=1.5 ,
      main="Running Proportion of Heads" , cex.main=1.5 )
# Plot a dotted horizontal reference line:
abline( h=pHeads , lty="dotted" )
# Display the beginning of the flip sequence:
flipLetters = paste( c("T","H")[flipSequence[1:10]+1] , collapse="" )
displayString = paste0( "Flip Sequence = " , flipLetters , "..." )
text( N , .3 , displayString , adj=c(1,0.5) , cex=1.3 )
# Display the relative frequency at the end of the sequence.
text( N , .2 , paste("End Proportion =",runProp[N]) , adj=c(1,0.5) , cex=1.3 )
```
## Exercise 4.3
```{r}
## Determine the exact probability of drawing a 10 from a shuffled pinochle deck. (In a pinochle deck, there are 48 cards. There are six values: 9, 10, Jack, Queen, King, Ace. There are two copies of each value in each of the standard four suits: hearts, clubs, spades, diamonds)

# a) what is the probability of getting a 10
prob10 = 8/48
show(round(prob10, 2))

## b) probability of getting a 10 or a Jack
probJ = 8/48
prob10orJ = prob10 + probJ
show(round(prob10orJ, 2))

```
## Exercise 4.4
```{r}
# consider a spinner with a [0,1] scale on its circumference. Suppose that the spinner is slanted or magnetized or bent in some way such that it is biased, and its probability density function is p(x) = 6x(1-x) over the interval x E [0,1].

# a) adapt the program IntegralOfDensity.R to plot this density function and approximate its integral.

source("DBDA2E-utilities.R")
# Graph of normal probability density function, with comb of intervals.
#meanval = 0.0               # Specify mean of distribution.
#sdval = 0.2                 # Specify standard deviation of distribution.
xlow  = 0 # Specify low end of x-axis.
xhigh = 1 # Specify high end of x-axis.
dx = .01  # Specify interval width on x-axis
# Specify comb of points along the x axis:
x = seq( from = xlow , to = xhigh , by = dx )
# Compute y values, i.e., probability density at each value of x:
y = 6 * x * (1-x)
# Plot the function. "plot" draws the intervals. "lines" draws the bell curve.
openGraph(width=7,height=5)
plot( x , y , type="h" , lwd=1 , cex.axis=1.5
	, xlab="x" , ylab="p(x)" , cex.lab=1.5 ,
	, main="Spinner Probability Density: 6x(1-x)" , cex.main=1.5 )
lines( x , y , lwd=3 ,  col="skyblue" )
# Approximate the integral as the sum of width * height for each interval.
area = sum( dx * y )
# Display info in the graph.
text( 0.7, .9*max(y) , bquote( paste(Delta , "x = " ,.(dx)) )
       , adj=c(0,.5) , cex=1.5 )
text( 0.6 , .75*max(y) ,
       bquote(
         paste( sum(,x,) , " " , Delta , "x p(x) = " , .(signif(area,3)) )
       ) , adj=c(0,.5) , cex=1.5 )
# Save the plot to an EPS file.
saveGraph(here::here("figs", "IntegralOfDensity.jpg"))

# b) Derive the exact integral using calculus (did this on slides in class)
# c) does this function satisfy equation 4.3? yes, because dx p(x) = 1
# d) maximal value of p(x) = 1.5, at E(x) = .5
```
## Exercise 4.5
```{r}
# a) adapt code from IntegralOfDensity.R to determine (approximately) the probability mass under the normal curve from x = mu - sigma to x = mu + sigma.

source("DBDA2E-utilities.R")
# Graph of normal probability density function, with comb of intervals.
meanval = 0.0               # Specify mean of distribution.
sdval = 0.2                 # Specify standard deviation of distribution.
xlow  = meanval - 1*sdval # Specify low end of x-axis.
xhigh = meanval + 1*sdval # Specify high end of x-axis.
dx = sdval/70               # Specify interval width on x-axis, play around with this one a bit, it's fun, and gives different area values!
# Specify comb of points along the x axis:
x = seq( from = xlow , to = xhigh , by = dx )
# Compute y values, i.e., probability density at each value of x:
y = ( 1/(sdval*sqrt(2*pi)) ) * exp( -.5 * ((x-meanval)/sdval)^2 )
# Plot the function. "plot" draws the intervals. "lines" draws the bell curve.
openGraph(width=7,height=5)
plot( x , y , type="h" , lwd=1 , cex.axis=1.5
	, xlab="x" , ylab="p(x)" , cex.lab=1.5 ,
	, main="Normal Probability Density" , cex.main=1.5 )
lines( x , y , lwd=3 ,  col="skyblue" )
# Approximate the integral as the sum of width * height for each interval.
area = sum( dx * y )
# Display info in the graph.
text( meanval - .5*sdval, .9*max(y) , bquote( paste(mu ," = " ,.(meanval)) )
      , adj=c(1,.5) , cex=1.5 )
text( meanval - .5*sdval , .75*max(y) , bquote( paste(sigma ," = " ,.(sdval)) )
      , adj=c(1,.5) , cex=1.5 )
text( meanval + 0.1*sdval , .9*max(y) , bquote( paste(Delta , "x = " ,.(dx)) )
      , adj=c(0,.5) , cex=1.5 )
text( meanval + 0.1*sdval , .75*max(y) ,
      bquote(
        paste(sum(,x,) , " " , Delta , "x p(x) = " , .(signif(area,3)) )
      ) , adj=c(0,.5) , cex=1.5 )
# Save the plot to an EPS file.
saveGraph(here::here("figs", "IntegralOfDensityNormal.jpg"))

# b) Now use the normal curve to describe the following belief. Suppose you believe that women's heights follow a bell-shaped distribution centered at 162 cm with about two-thirds of all women having heights between 147 and 177 cm, what should be the mu and sigma parameter values?
 # mu = 162
# sigma = 15
```
## Exercise 4.6
```{r}
propGrade <- c(.2, .2, .6)
gradeFood <- matrix(c(0.3, 0.6, 0.1, 0.6, 0.3, 0.1, 0.3, 0.1, 0.6), ncol = 3, byrow = TRUE)
colnames(gradeFood) <- c("Ice Cream", "Fruit", "French Fries")
rownames(gradeFood) <- c("1st graders", "6th graders", "11th graders")
gradeFood <- as.table(gradeFood)
jointGradeFood <- gradeFood*propGrade

## are grade and food independent? 

pFirstXpIceCream = .2 * .3
pIceCreamXpFirst = .36 * .20


```

 